theme: jekyll-theme-leap-day
baseurl: ""
markdown: redcarpet
redcarpet:
    extensions: [tables]
safe: false
pygments: true
excerpt_separator: "\n\n\n"
paginate: 5
sitemapurl: "http://zhoulitong.github.io/"
